{% set name = "goodtables-pandas-py" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/goodtables-pandas-py-{{ version }}.tar.gz
  sha256: 194171af746bf96bb2198866b31aa76cd5b4547a77f6dd55d821ad97ef268406

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0,<2.0.0
    - python {{ python_min }}
  run:
    - frictionless >=3.34.0,<4.0.0
    - pandas >=1.1.3,<2.0.0
    - python >={{ python_min }},<4.0
    - typing-extensions >=3.7.4,<4.0.0

test:
  imports:
    - goodtables_pandas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ezwelty/goodtables-pandas-py
  summary: Read and validate Frictionless Data Tabular Data Packages with pandas.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ezwelty
